### PR TITLE
Fix bug where the RSA object that is created with GetRSAPublicKey is not disposed.

### LINKED ISSUE #863: RSATrustedSigning is not disposing the RSA object created with GetRSAPublicKey
The RSATrustedSigning class is not disposing the RSA object that is created with GetRSAPublicKey in the PublicKey property.

### PR DESCRIPTION
**Pull request by dlemstra**
Fixes #863.

### CODE REVIEW

File: src/Sign.SignatureProviders.TrustedSigning/RSATrustedSigning.cs [hunk 1]
```diff
@@ -15,7 +15,7 @@ internal sealed class RSATrustedSigning : RSA
         private readonly CertificateProfileClient _client;
         private readonly string _accountName;
         private readonly string _certificateProfileName;
-        private readonly X509Certificate2 _certificate;
+        private readonly RSA _rsaPublicKey;
```
Comment (erdembayar) [inline src/Sign.SignatureProviders.TrustedSigning/RSATrustedSigning.cs:18]: X509Certificate2 is not specifically only for RSA, does it break anything now?

Comment (dlemstra) [reply src/Sign.SignatureProviders.TrustedSigning/RSATrustedSigning.cs:18]: We were doing `_certificate.GetRSAPublicKey()!` in the property I moved that to the constructor to make sure it's disposed after we are done using it. Functionally nothing was changed.

**Review by erdembayar — APPROVED** [review]

**Review by dtivel — APPROVED** [review]

**Comment by dtivel** [comment]
Thanks, @dlemstra!
